const amenityIcons = {
  swimming_pool: '/amenities/swimming_pool.svg',
  kids_play_area: '/amenities/kids_play_area.svg',
  kids_playground: '/amenities/kids_playground.svg',
  clubhouse: '/amenities/clubhouse.svg',
  fitness_cycle: '/amenities/fitness_cycle.svg',
  fitness_weightlift: '/amenities/fitness_weightlift.png',
  cctv: '/amenities/cctv.svg',
  sculpture: '/amenities/sculpture.png',
  temple: '/amenities/temple.png',
  waiting_lounge: '/amenities/waiting_lounge.png',
  walkway: '/amenities/walkway.png',
  gazebo_seating: '/amenities/gazebo_seating.svg',
  theater: '/amenities/theater.png',
  movie: '/amenities/movie.svg',
  senior_seating: '/amenities/senior_seating.png',
  banquet_hall: '/amenities/banquet_hall.png',
  garden: '/amenities/garden.png',
  terrace_seating: '/amenities/terrace_seating.png',
  lift: '/amenities/lift.png',
  canteen: '/amenities/canteen.png',
  fire_extinguisher: '/amenities/fire_extinguisher.png',
  table_tennis: '/amenities/table-tennis.png',
  wheelchair: '/amenities/whelechair.svg',
  job_application: '/amenities/job_application.svg',
  home_appliance: '/amenities/home-appliance.png',
  parking: '/amenities/parking.png',
  power_backup: '/amenities/power-backup.png',
}
export default amenityIcons